[package]
name = "rnytd"
version = "0.1.4"
edition = "2024"
description = "A simple and interactive command-line tool for downloading YouTube videos and extracting audio."
repository = "https://github.com/RAJ8664/CLI/tree/main/rnytd"
homepage = "https://github.com/RAJ8664/CLI/tree/main/rnytd"
license = "MIT"
keywords = ["youtube", "download", "audio", "cli", "video"]
categories = ["command-line-utilities"]

[dependencies]
dialoguer = "0.11"
indicatif = "0.17"
console = "0.15"
